'reinit'
'sdfopen f://david3.nc'
'set t 1'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 07:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc1.png'

'reinit'
'sdfopen f://david3.nc'
'set t 2'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 08:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc2.png'

'reinit'
'sdfopen f://david3.nc'
'set t 3'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 09:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc3.png'

'reinit'
'sdfopen f://david3.nc'
'set t 4'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 10:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc4.png'

'reinit'
'sdfopen f://david3.nc'
'set t 5'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 11:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc5.png'

'reinit'
'sdfopen f://david3.nc'
'set t 6'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 12:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc6.png'

'reinit'
'sdfopen f://david3.nc'
'set t 7'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 13:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc7.png'

'reinit'
'sdfopen f://david3.nc'
'set t 8'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 14:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc8.png'

'reinit'
'sdfopen f://david3.nc'
'set t 9'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 15:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc9.png'

'reinit'
'sdfopen f://david3.nc'
'set t 10'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 16:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc10.png'

'reinit'
'sdfopen f://david3.nc'
'set t 11'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 17:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc11.png'

'reinit'
'sdfopen f://david3.nc'
'set t 12'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 18:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc12.png'

'reinit'
'sdfopen f://david3.nc'
'set t 13'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 19:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc13.png'

'reinit'
'sdfopen f://david3.nc'
'set t 14'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 20:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc14.png'

'reinit'
'sdfopen f://david3.nc'
'set t 15'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 21:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc15.png'

'reinit'
'sdfopen f://david3.nc'
'set t 16'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 22:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc16.png'

'reinit'
'sdfopen f://david3.nc'
'set t 17'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\22 Maret 2023 23:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc17.png'

'reinit'
'sdfopen f://david3.nc'
'set t 18'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\23 Maret 2023 00:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc18.png'

'reinit'
'sdfopen f://david3.nc'
'set t 19'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\23 Maret 2023 01:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc19.png'

'reinit'
'sdfopen f://david3.nc'
'set t 20'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\23 Maret 2023 02:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc20.png'

'reinit'
'sdfopen f://david3.nc'
'set t 21'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\23 Maret 2023 03:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc21.png'

'reinit'
'sdfopen f://david3.nc'
'set t 22'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\23 Maret 2023 04:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc22.png'

'reinit'
'sdfopen f://david3.nc'
'set t 23'
'set display white'
'set mpdset hires'
'set gxout shaded'
'set csmooth on'
'd tcc'
'draw title Total Tutupan Awan\23 Maret 2023 05:00:00 WIB'
'cbar'
'printim C:\OpenGrADS-2.2\image\tcc23.png'
