# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFFU84aMhFCfh8K2S1kDbaEnwyf3ox6_
"""

import cv2
import numpy as np

img = cv2.imread('hilal.png')

c = 250/(np.log(1 + np.max(img)))

log_transformed = c * np.log(130 + img)

log_transformed = np.array(log_transformed, dtype = np.uint8)

cv2.imwrite('log_transformed.png', log_transformed)
cv2.imshow("Original image", img)
cv2.imshow('log_transformed.png', log_transformed)
cv2.waitKey(0)
cv2.destroyAllWindows()