# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFFU84aMhFCfh8K2S1kDbaEnwyf3ox6_
"""

import cv2 as cv
import os
import matplotlib.pyplot as plt

def goodCornerDetection():
    root = os.getcwd()
    imgPath = os.path.join(root, 'Hilal.png')
    img = cv.imread(imgPath)
    imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)
    imgGray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    maxCorners = 200
    qualityLevel = 0.01
    minDistance = 20
    corners = cv.goodFeaturesToTrack(imgGray, maxCorners, qualityLevel, minDistance)

    for corner in corners:
        x, y = corner.ravel()
        cv.circle(imgRGB, (x, y), 10, (255, 0, 0), -1)

    plt.figure()
    plt.imshow(imgRGB)
    plt.show()

if __name__ == '__main__':
    goodCornerDetection()