# -*- coding: utf-8 -*-
"""PLOT NILAI MSE DAN PSNR TA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ZniZdjTF-UDhIxc1F9jUwGC5vkrgM6L
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
import locale
from matplotlib.ticker import AutoMinorLocator, StrMethodFormatter

#Nilai MSE

data =  pd.read_excel(r'MSE_NEW.xlsx')
data

citra = data["CITRA"]
clahe = data["CLAHE"]
cs = data["CS"]
gc = data["GC"]

plt.figure(figsize=(12,6))
ax = plt.axes()
plt.title('Grafik Mean Square Error (MSE)', size=15)
plt.xlabel('Nomor citra', size=15)
plt.ylabel('MSE', size=15)
plt.grid(True)
plt.plot(citra,clahe, 'r^-')
plt.plot(citra,cs, 'bo-')
plt.plot(citra,gc, 'gs-')
# ax.set_xticks([1,2,3,4,5,6,7,8,9,10])
ax.set_yticks([0.05,0.075,0.1,0.125,0.15,0.175,0.2,0.225,0.250,0.275,0.30,0.0325])
ax.legend(["CLAHE","Contras Stretching","Gamma Correction"], loc='upper left', framealpha=0.5, frameon=True)
plt.gca().yaxis.set_minor_locator(AutoMinorLocator())
plt.show()
plt.savefig('mse.png', format='png', dpi=600)

#Nilai PNSR

data1 =  pd.read_excel(r'PSNR_NEW.xlsx')
data1

citra1 = data1["CITRA"]
clahe1 = data1["CLAHE"]
cs1 = data1["CS"]
gc1 = data1["GC"]

plt.figure(figsize=(12,6))
ax = plt.axes()
plt.title('Grafik Peak Signal-to-Noise Ratio (PSNR)', size=15)
plt.xlabel('Nomor citra', size=15)
plt.ylabel('PSNR (dB)', size=15)
plt.grid(True)
plt.plot(citra1,clahe1, 'r^-')
plt.plot(citra1,cs1, 'bo-')
plt.plot(citra1,gc1, 'gs-')
# ax.set_xticks([1,2,3,4,5,6,7,8,9,10])
ax.set_yticks([29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])
ax.legend(["CLAHE","Contras Stretching","Gamma Correction"], loc='upper left', framealpha=1, frameon=True)
plt.gca().yaxis.set_minor_locator(AutoMinorLocator())
plt.show()
plt.savefig('psnr.png', format='png', dpi=600)

